services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  eventstoredb:
    image: eventstore/eventstore:latest
    container_name: eventstoredb
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "All"
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    volumes:
      - eventstore-data:/var/lib/eventstore
    ports:
      - "2113:2113" # HTTP Port
      - "1113:1113" # TCP Port
    networks:
      - esdb-network

networks:
  esdb-network:
    driver: bridge

volumes:
  eventstore-data: